    - name: Desplegar Frontend vía SSM (Contenedor Individual)
      run: |
        # Extraemos la URL base del registro directamente desde la URL del repositorio
        ECR_REGISTRY=$(echo "${{ secrets.ECR_REPO_URL_FRONTEND }}" | cut -d'/' -f1)

        COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Desplegar contenedor tienda-frontend" \
          --parameters "{\"commands\":[
            \"set -x\",
            \"aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY\",
            \"docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest\",
            \"docker stop tienda-frontend || true\",
            \"docker rm tienda-frontend || true\",
            \"docker run -d --name tienda-frontend -p 80:80 ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest\"
          ]}" \
          --query "Command.CommandId" \
          --output text)
        
        echo "Comando SSM enviado con ID: $COMMAND_ID"
        echo "Esperando confirmación de la EC2..."
        
        # Esto hace que el workflow falle en GitHub si la EC2 no logra levantar el contenedor
        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id ${{ secrets.EC2_FRONTEND_INSTANCE_ID }}
